"""
Módulo de configuración para el servidor MCP de Pitágoras.
"""

from config.settings import (
    API_BASE_URL,
    AUTH_TOKEN,
    DEFAULT_USER_EMAIL,
    CUSTOMERS_ENDPOINT,
    ADWORDS_REPORT_ENDPOINT,
    FACEBOOK_REPORT_ENDPOINT,
    ANALYTICS4_REPORT_ENDPOINT,
    TIME_PERIODS,
)

__all__ = [
    'API_BASE_URL',
    'AUTH_TOKEN',
    'DEFAULT_USER_EMAIL',
    'CUSTOMERS_ENDPOINT',
    'ADWORDS_REPORT_ENDPOINT',
    'FACEBOOK_REPORT_ENDPOINT',
    'ANALYTICS4_REPORT_ENDPOINT',
    'TIME_PERIODS',
]